# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\nuevoDocumentoDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(400, 534)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(380, 400))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/document.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet(_fromUtf8("QDialog{\n"
"    background:#fafafa\n"
"}\n"
"QLineEdit,QDateEdit,QDoubleSpinBox{\n"
"    padding:4px\n"
"}"))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(40, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label.setFont(font)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/document.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.labelTitulo = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setObjectName(_fromUtf8("labelTitulo"))
        self.verticalLayout_3.addWidget(self.labelTitulo)
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.nDocumentoLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nDocumentoLabel.setFont(font)
        self.nDocumentoLabel.setObjectName(_fromUtf8("nDocumentoLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.nDocumentoLabel)
        self.emisorLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.emisorLabel.setFont(font)
        self.emisorLabel.setObjectName(_fromUtf8("emisorLabel"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.emisorLabel)
        self.receptorLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.receptorLabel.setFont(font)
        self.receptorLabel.setObjectName(_fromUtf8("receptorLabel"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.receptorLabel)
        self.fechaLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fechaLabel.setFont(font)
        self.fechaLabel.setObjectName(_fromUtf8("fechaLabel"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.fechaLabel)
        self.fechaDateEdit = QtGui.QDateEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.fechaDateEdit.setFont(font)
        self.fechaDateEdit.setReadOnly(True)
        self.fechaDateEdit.setObjectName(_fromUtf8("fechaDateEdit"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.fechaDateEdit)
        self.labelNDocumento = QtGui.QLabel(Dialog)
        self.labelNDocumento.setIndent(4)
        self.labelNDocumento.setObjectName(_fromUtf8("labelNDocumento"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelNDocumento)
        self.labelEmisor = QtGui.QLabel(Dialog)
        self.labelEmisor.setIndent(4)
        self.labelEmisor.setObjectName(_fromUtf8("labelEmisor"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelEmisor)
        self.labelReceptor = QtGui.QLabel(Dialog)
        self.labelReceptor.setIndent(4)
        self.labelReceptor.setObjectName(_fromUtf8("labelReceptor"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.labelReceptor)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.line = QtGui.QFrame(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        self.line.setFont(font)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.sucursalLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sucursalLabel.setFont(font)
        self.sucursalLabel.setObjectName(_fromUtf8("sucursalLabel"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.sucursalLabel)
        self.sucursalLineEdit = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.sucursalLineEdit.setFont(font)
        self.sucursalLineEdit.setObjectName(_fromUtf8("sucursalLineEdit"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.SpanningRole, self.sucursalLineEdit)
        self.contracuentaLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.contracuentaLabel.setFont(font)
        self.contracuentaLabel.setObjectName(_fromUtf8("contracuentaLabel"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.contracuentaLabel)
        self.contracuentaLineEdit = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.contracuentaLineEdit.setFont(font)
        self.contracuentaLineEdit.setObjectName(_fromUtf8("contracuentaLineEdit"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.SpanningRole, self.contracuentaLineEdit)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.cuentaProveedoresClienteLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cuentaProveedoresClienteLabel.setFont(font)
        self.cuentaProveedoresClienteLabel.setObjectName(_fromUtf8("cuentaProveedoresClienteLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.cuentaProveedoresClienteLabel)
        self.cuentaProveedoresClienteLineEdit = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.cuentaProveedoresClienteLineEdit.setFont(font)
        self.cuentaProveedoresClienteLineEdit.setObjectName(_fromUtf8("cuentaProveedoresClienteLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.cuentaProveedoresClienteLineEdit)
        self.correlativoLabel = QtGui.QLabel(Dialog)
        self.correlativoLabel.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.correlativoLabel.setFont(font)
        self.correlativoLabel.setObjectName(_fromUtf8("correlativoLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.correlativoLabel)
        self.correlativoLineEdit = QtGui.QLineEdit(Dialog)
        self.correlativoLineEdit.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.correlativoLineEdit.setFont(font)
        self.correlativoLineEdit.setObjectName(_fromUtf8("correlativoLineEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.SpanningRole, self.correlativoLineEdit)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.glosaLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.glosaLabel.setFont(font)
        self.glosaLabel.setObjectName(_fromUtf8("glosaLabel"))
        self.verticalLayout_3.addWidget(self.glosaLabel)
        self.glosaLineEdit = QtGui.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.glosaLineEdit.setFont(font)
        self.glosaLineEdit.setObjectName(_fromUtf8("glosaLineEdit"))
        self.verticalLayout_3.addWidget(self.glosaLineEdit)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.montoExcentoLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.montoExcentoLabel.setFont(font)
        self.montoExcentoLabel.setObjectName(_fromUtf8("montoExcentoLabel"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.montoExcentoLabel)
        self.montoExcentoSpinBox = QtGui.QDoubleSpinBox(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.montoExcentoSpinBox.setFont(font)
        self.montoExcentoSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.montoExcentoSpinBox.setDecimals(0)
        self.montoExcentoSpinBox.setMaximum(1999999999.0)
        self.montoExcentoSpinBox.setObjectName(_fromUtf8("montoExcentoSpinBox"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.SpanningRole, self.montoExcentoSpinBox)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.line_2)
        self.verticalLayout_3.addLayout(self.formLayout_6)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.montoTotalLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.montoTotalLabel.setFont(font)
        self.montoTotalLabel.setIndent(7)
        self.montoTotalLabel.setObjectName(_fromUtf8("montoTotalLabel"))
        self.horizontalLayout_3.addWidget(self.montoTotalLabel)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.montoTotalLabel_3 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.montoTotalLabel_3.setFont(font)
        self.montoTotalLabel_3.setObjectName(_fromUtf8("montoTotalLabel_3"))
        self.gridLayout_4.addWidget(self.montoTotalLabel_3, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setContentsMargins(-1, 4, -1, 4)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.activoFijoLabel = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.activoFijoLabel.setFont(font)
        self.activoFijoLabel.setObjectName(_fromUtf8("activoFijoLabel"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.activoFijoLabel)
        self.activoFijoCheckBox = QtGui.QCheckBox(Dialog)
        self.activoFijoCheckBox.setStyleSheet(_fromUtf8("margin-top: 2px"))
        self.activoFijoCheckBox.setObjectName(_fromUtf8("activoFijoCheckBox"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.activoFijoCheckBox)
        self.verticalLayout_3.addLayout(self.formLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 8, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 8, 1, 1)
        self.fechaLabel.setBuddy(self.fechaDateEdit)
        self.sucursalLabel.setBuddy(self.sucursalLineEdit)
        self.contracuentaLabel.setBuddy(self.contracuentaLineEdit)
        self.cuentaProveedoresClienteLabel.setBuddy(self.cuentaProveedoresClienteLineEdit)
        self.glosaLabel.setBuddy(self.glosaLineEdit)
        self.montoExcentoLabel.setBuddy(self.montoExcentoSpinBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.reject)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.fechaDateEdit, self.sucursalLineEdit)
        Dialog.setTabOrder(self.sucursalLineEdit, self.cuentaProveedoresClienteLineEdit)
        Dialog.setTabOrder(self.cuentaProveedoresClienteLineEdit, self.contracuentaLineEdit)
        Dialog.setTabOrder(self.contracuentaLineEdit, self.glosaLineEdit)
        Dialog.setTabOrder(self.glosaLineEdit, self.montoExcentoSpinBox)
        Dialog.setTabOrder(self.montoExcentoSpinBox, self.activoFijoCheckBox)
        Dialog.setTabOrder(self.activoFijoCheckBox, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.correlativoLineEdit)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Nuevo Documento", None))
        self.labelTitulo.setText(_translate("Dialog", "Nuevo Documento Electrónico", None))
        self.nDocumentoLabel.setText(_translate("Dialog", "Nº Documento", None))
        self.emisorLabel.setText(_translate("Dialog", "Emisor", None))
        self.receptorLabel.setText(_translate("Dialog", "Receptor", None))
        self.fechaLabel.setText(_translate("Dialog", "Fecha", None))
        self.fechaDateEdit.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd", None))
        self.labelNDocumento.setText(_translate("Dialog", "Numero documento", None))
        self.labelEmisor.setText(_translate("Dialog", "Emisor", None))
        self.labelReceptor.setToolTip(_translate("Dialog", "algo", None))
        self.labelReceptor.setAccessibleName(_translate("Dialog", "algoan", None))
        self.labelReceptor.setAccessibleDescription(_translate("Dialog", "algoad", None))
        self.labelReceptor.setText(_translate("Dialog", "Receptor", None))
        self.sucursalLabel.setText(_translate("Dialog", "Sucursal", None))
        self.sucursalLineEdit.setText(_translate("Dialog", "1", None))
        self.sucursalLineEdit.setPlaceholderText(_translate("Dialog", "Sucursal", None))
        self.contracuentaLabel.setText(_translate("Dialog", "Contracuenta", None))
        self.contracuentaLineEdit.setPlaceholderText(_translate("Dialog", "Número contracuenta", None))
        self.cuentaProveedoresClienteLabel.setText(_translate("Dialog", "Cuenta Proveedores/Cliente", None))
        self.cuentaProveedoresClienteLineEdit.setPlaceholderText(_translate("Dialog", "Numero de cuenta", None))
        self.correlativoLabel.setText(_translate("Dialog", "Correlativo", None))
        self.correlativoLineEdit.setText(_translate("Dialog", "0", None))
        self.correlativoLineEdit.setPlaceholderText(_translate("Dialog", "Correlativo", None))
        self.glosaLabel.setToolTip(_translate("Dialog", "Explicación o descripción de la factura", None))
        self.glosaLabel.setText(_translate("Dialog", "Glosa", None))
        self.glosaLineEdit.setToolTip(_translate("Dialog", "Explicación o descripción de la factura", None))
        self.glosaLineEdit.setPlaceholderText(_translate("Dialog", "Glosa", None))
        self.montoExcentoLabel.setText(_translate("Dialog", "Monto Excento", None))
        self.montoExcentoSpinBox.setPrefix(_translate("Dialog", "$ ", None))
        self.montoTotalLabel.setText(_translate("Dialog", "$ 0", None))
        self.montoTotalLabel_3.setText(_translate("Dialog", "Monto Total", None))
        self.activoFijoLabel.setText(_translate("Dialog", "Activo Fijo", None))
        self.pushButton.setText(_translate("Dialog", "Guardar", None))
        self.pushButton_2.setText(_translate("Dialog", "Cancelar", None))

import images_rc
